Add filing controller and service handler.
companieshouse/registered-email-address-api pull request #16
Opened 2023-05-22 10:09 UTC by mike-kelly-ch

As per title. Adds a `/filings` `GET` endpoint created on the REA api so that filing data can be retrieved.

Ticket -> https://companieshouse.atlassian.net/browse/ECCT-158

2023-05-22 15:31 UTC, adeharrison-ch requested changes

2023-05-23 07:39 UTC, mike-kelly-ch commented on src/test/java/uk/gov/companieshouse/registeredemailaddressapi/unit/controller/RegisteredEmailAddressControllerFilingTest.java
> +public class RegisteredEmailAddressControllerFilingTest {
🤦

2023-05-23 08:06 UTC, adeharrison-ch approved these changes
LGTM

2023-05-23 09:07 UTC, carolineward2 approved these changes

2023-05-23 09:07 UTC, carolineward2 approved these changes

2023-05-23 09:11 UTC, merged